[package]
name = "terminal"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/terminal.rs"
doctest = false

[dependencies]
alacritty_terminal.workspace = true
anyhow.workspace = true
collections.workspace = true
dirs.workspace = true
fancy-regex.workspace = true
futures.workspace = true
gpui.workspace = true
itertools.workspace = true
libc.workspace = true
log.workspace = true
release_channel.workspace = true
schemars.workspace = true
serde.workspace = true
serde_derive.workspace = true
settings.workspace = true
sysinfo.workspace = true
smol.workspace = true
task.workspace = true
theme.workspace = true
thiserror.workspace = true
util.workspace = true
unicode-segmentation.workspace = true
regex.workspace = true
workspace-hack.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[dev-dependencies]
rand.workspace = true
regex.workspace = true
serde_json.workspace = true
